name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt install libsdl2-dev cmake build-essential
      - name: Build
        run: bash build.sh
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: build-linux/chip8

  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install MinGW
        run: sudo apt install mingw-w64 cmake
      - name: Download SDL2
        run: |
          cd build-windows
          wget https://github.com/libsdl-org/SDL/releases/download/release-2.28.5/SDL2-devel-2.28.5-mingw.tar.gz
          tar xzf SDL2-devel-2.28.5-mingw.tar.gz
      - name: Build
        run: bash build.sh
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: build-windows/chip8.exe
